### ISSUE TITLE
Not using the correct Application instance

### ISSUE THREAD

**Issue by RyanSimon** [jaykallen/DaggerKotlin#1]
https://github.com/jaykallen/DaggerKotlin/blob/1560c1a48734b343972c9b213f70fc163ae7c0b0/app/src/main/java/com/procatdt/dagger/MainActivity.kt#L20

Should be
```
        (application as StartApp).injector.inject(this)
```

**Comment by RyanSimon** [comment]
Same goes for your other Activity

**Comment by jaykallen** [comment]
This has been corrected with a companion object in the application class
`    companion object {
        lateinit var instance: StartApp
            private set
    }`
